import Foundation

/// **What goes on the spawn menu: the ones he pinned, and the ones he has
/// actually been working in.**
///
/// `SpawnFolderMenu` used to name six folders hardcoded in Swift — the projects
/// Victor happened to be working on the afternoon it was written. That list is
/// wrong the week after and wrong *silently*: a project missing from it costs
/// the first sentence of every session started in it, spoken out loud to tell
/// the agent where it is, which is the exact cost the menu exists to remove.
///
/// Victor's ask, 2026-09-08: *"să determin care sunt proiectele în care am
/// lucrat … să le adaugi sub o linie separatoare … pe lângă cele fixate de sus"*.
/// So the menu has two halves now, and this file is where each of them comes
/// from:
///
/// | half | source | who decides |
/// |---|---|---|
/// | above the line | `PinnedProjects` — a file he edits by clicking a star | him, explicitly |
/// | below the line | `RecentProjects` — a ranking read off Claude Code's transcripts | measurement |
///
/// **The two are read the same way and written very differently**, and that is
/// the point of keeping them in one file: a pin is a decision and survives
/// everything, while a recent is an observation and is replaced wholesale by
/// every scan.

// MARK: - Recents

/// The projects he has burned the most tokens in lately, as measured by
/// `helpers/recent_projects.py` and left on disk for this app to read.
///
/// **Nothing here does the measuring.** That is deliberate and it is the whole
/// performance story Victor asked for — *"nu vreau să mănânci token ca să
/// evaluezi unde s-au petrecut mulți token … dar nici să execuți asta la fiecare
/// click. Vreau ceva performant, regulat"*. Opening the menu reads one small
/// JSON file. The scan that produced it is a separate process that runs at most
/// once a day, in the background, and takes about two seconds; see
/// `refreshIfStale`.
enum RecentProjects {

    struct Project {
        let name: String
        let path: String
        let score: Double
    }

    /// Beside the outbox, and not in Caches — which is the opposite of the call
    /// `MessageLog` makes one file over. That page is regenerated by the click
    /// that opens it, so losing it costs nothing; this one is regenerated *at
    /// most once a day* by a process nobody is waiting on, so a purge would mean
    /// the menu comes up with no recents at all until tomorrow.
    static var url: URL { Outbox.home.appendingPathComponent("recent-projects.json") }

    /// How many recents the menu shows. Victor's number: *"m-ar interesa să-mi
    /// faci un top 5"*.
    static let count = 5

    /// **A day.** The ranking is over a fortnight, so a scan a few hours old
    /// cannot be meaningfully wrong — and this app is a login item that stays up
    /// for days at a time, which is why staleness is a question asked at the
    /// gesture rather than only at launch.
    static let maxAge: TimeInterval = 24 * 3600

    /// The ranking as it stands on disk, best first. An absent or unreadable
    /// file is an empty list: the menu then shows the pinned half alone, which
    /// is exactly what it showed before any of this existed.
    static func load() -> [Project] {
        guard let data = try? Data(contentsOf: url),
              let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let rows = root["projects"] as? [[String: Any]]
        else { return [] }
        return rows.compactMap { row in
            guard let name = row["name"] as? String,
                  let path = row["path"] as? String,
                  // A project can be deleted between a scan and a menu. The
                  // launcher falls back to `$HOME` on a failed `cd`, which is
                  // the one destination nobody meant.
                  FileManager.default.fileExists(atPath: path)
            else { return nil }
            return Project(name: name, path: path,
                           score: (row["score"] as? NSNumber)?.doubleValue ?? 0)
        }
    }

    /// The top `count` he has **not** pinned, in alphabetical order.
    ///
    /// **Ranked to choose them, sorted to show them** — both halves of that are
    /// his: *"alea să fie … în ordine descrescătoare după… nu, alfabetic"*. The
    /// score decides *which five*, and then the eye gets a list it can find a
    /// name in without reading all of it. A leaderboard that reorders itself
    /// between two openings of the same menu is one where the row he reached for
    /// last time is somewhere else.
    ///
    /// Pinned projects are removed rather than shown twice: the same folder on
    /// both sides of the separator says the separator means nothing.
    static func offered(excluding pinned: Set<String>) -> [Project] {
        load()
            .filter { !pinned.contains($0.path) }
            .prefix(count)
            .sorted { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
    }

    // MARK: - Keeping it fresh

    private static var refreshing = false

    /// Run the scan in the background if what is on disk is older than a day.
    ///
    /// **Called from the gesture, and it is still not work done at the
    /// gesture**: the check is one `stat`, and on the one day in a hundred it
    /// says yes, what happens is a detached process that this app never waits
    /// on. The menu that triggered the scan shows yesterday's answer; today's
    /// lands for the next one. Nothing about the ranking is urgent enough to
    /// justify a menu that appears two seconds after the sentence started.
    ///
    /// It is asked here **and** at launch because neither alone covers how this
    /// app is used: it is a login item that can stay up for a week (so launch is
    /// not often enough) and it can also be restarted five times in an afternoon
    /// while something is being built (so launch alone would rescan five times —
    /// which the age check is what prevents).
    static func refreshIfStale() {
        guard !refreshing else { return }
        let age = (try? FileManager.default.attributesOfItem(atPath: url.path)[.modificationDate])
            .flatMap { ($0 as? Date).map { Date().timeIntervalSince($0) } }
        if let age, age < maxAge { return }
        refresh()
    }

    /// Run it now, whatever the file's age.
    static func refresh() {
        guard !refreshing, let helper = helperPath else {
            if helperPath == nil { Log.info("recents: recent_projects.py not found beside the binary") }
            return
        }
        refreshing = true
        let p = Process()
        // **Apple's python3, deliberately, and not `Transcriber.pythonPath`.**
        // That one probes for an interpreter carrying `mlx_whisper`, because the
        // helper it launches imports it. This script is pure standard library,
        // so the interpreter that is always present and needs no probing is the
        // right one — and the probe itself costs several process launches.
        p.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
        p.arguments = [helper, "--out", url.path]
        p.standardOutput = FileHandle.nullDevice
        p.standardError = FileHandle.nullDevice
        p.terminationHandler = { proc in
            refreshing = false
            Log.info("recents: scan finished (status \(proc.terminationStatus))")
        }
        do {
            try p.run()
            Log.info("recents: scanning transcripts in the background")
        } catch {
            refreshing = false
            Log.info("recents: could not start the scan — \(error)")
        }
    }

    /// Beside the binary in the installed `.app`, in `helpers/` for a
    /// `swift build` run. Same shape and the same reason as
    /// `Transcriber.helperPath`: a developer run and an installed run both work
    /// without a switch.
    private static var helperPath: String? {
        var candidates: [URL] = []
        if let res = Bundle.main.resourcePath {
            candidates.append(URL(fileURLWithPath: res).appendingPathComponent("recent_projects.py"))
        }
        let exe = URL(fileURLWithPath: CommandLine.arguments[0],
                      relativeTo: URL(fileURLWithPath: FileManager.default.currentDirectoryPath))
            .standardizedFileURL.resolvingSymlinksInPath()
        var dir = exe.deletingLastPathComponent()
        for _ in 0..<4 {
            candidates.append(dir.appendingPathComponent("helpers/recent_projects.py"))
            candidates.append(dir.appendingPathComponent("recent_projects.py"))
            dir = dir.deletingLastPathComponent()
        }
        return candidates.first { FileManager.default.fileExists(atPath: $0.path) }?.path
    }
}

// MARK: - Pins

/// The projects he put above the line himself, by clicking the star.
///
/// **A pin is the answer to a question measurement cannot answer**: a repo he is
/// about to start working in has no transcripts behind it yet, and one he keeps
/// coming back to between long gaps drops out of a fortnight's ranking exactly
/// when he needs it. The star is how he overrules the measurement in both
/// directions — and unpinning is not a delete: *"acel proiect să apară în lista
/// de proiecte recente, doar dacă am deschis recent în acel folder vreo muncă"*,
/// which is what falling back into `RecentProjects` already does, with the
/// qualification built in.
enum PinnedProjects {

    static var url: URL { Outbox.home.appendingPathComponent("pinned-projects.json") }

    /// **What the menu held before the star existed**, and what a fresh install
    /// starts with. Seeding rather than starting empty is the continuity call:
    /// this list is the six folders the menu has named for days, and the first
    /// spawn after an update should show him the menu he knows, with a star
    /// beside each row explaining how it got that way.
    private static let seed = ["victor-macos-addons", "training-assistant",
                              "walkie-talkie", "victor-vsc", "petclinic", "human-review"]

    private static var cached: [String]?

    /// The pinned paths, in the order they were written. Order does not matter —
    /// the menu sorts — but rewriting the file on every read would.
    static func paths() -> [String] {
        if let cached { return cached }
        let stored: [String]
        if let data = try? Data(contentsOf: url),
           let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let rows = root["pinned"] as? [String] {
            stored = rows
        } else {
            stored = seed.map {
                FileManager.default.homeDirectoryForCurrentUser
                    .appendingPathComponent("workspace").appendingPathComponent($0).path
            }
        }
        // A folder that is gone is dropped on the way out but left in the file:
        // an external disk or a checkout he will make again should not cost him
        // the pin. Only a click takes one off.
        let live = stored.filter { FileManager.default.fileExists(atPath: $0) }
        cached = live
        return live
    }

    static func isPinned(_ path: String) -> Bool { paths().contains(path) }

    /// Star or unstar, and write it down. Returns the new state.
    @discardableResult
    static func toggle(_ path: String) -> Bool {
        var live = paths()
        let pinning = !live.contains(path)
        if pinning { live.append(path) } else { live.removeAll { $0 == path } }
        cached = live
        save(live)
        return pinning
    }

    private static func save(_ paths: [String]) {
        let payload: [String: Any] = ["pinned": paths]
        guard let data = try? JSONSerialization.data(withJSONObject: payload,
                                                     options: [.prettyPrinted, .sortedKeys])
        else { return }
        try? FileManager.default.createDirectory(at: Outbox.home,
                                                 withIntermediateDirectories: true)
        try? data.write(to: url, options: .atomic)
    }
}
